// Generated by CoffeeScript 1.6.2
"use strict";
var compute;

compute = function(y, xmin, dx, columns, maxIterations) {
  var a, b, ct, i, iterationCounts, x0, y0, _i, _ref, _ref1, _ref2;

  iterationCounts = [];
  for (i = _i = 0; 0 <= columns ? _i <= columns : _i >= columns; i = 0 <= columns ? ++_i : --_i) {
    _ref = [xmin + i * dx, y], x0 = _ref[0], y0 = _ref[1];
    _ref1 = [x0, y0, 0], a = _ref1[0], b = _ref1[1], ct = _ref1[2];
    while (a * a + b * b < 4.1) {
      ct++;
      if (ct > maxIterations) {
        ct = -1;
        break;
      }
      _ref2 = [a * a - b * b + x0, 2 * a * b + y0], a = _ref2[0], b = _ref2[1];
    }
    iterationCounts[i] = ct;
  }
  return iterationCounts;
};

this.onmessage = function(msg) {
  var counts, job;

  job = msg.data;
  counts = compute(job.y, job.xmin, job.dx, job.columns, job.maxIterations);
  return postMessage({
    workerNum: job.workerNum,
    jobNum: job.jobNum,
    row: job.row,
    iterationCounts: counts
  });
};
